version: '3.9'

services:
    js:
        image: react-node:0.1
        container_name: Node.js
        ports:
            - "8810:5173"
        tty: true
        volumes:
            - ./src:/var/www/app
        networks:
            - net


networks:
    net:
        driver: bridge
